### PR TITLE
feat: add french translation

### PR DESCRIPTION
**Pull request by Gregcop1**

### CODE REVIEW

**Comment by Zales0123** [comment]
Hello @Gregcop1! Thank you for your contribution, however, on Sylius repository we manage only English translations. To contribute to other languages, please, use our Crowdin project page - https://crowdin.com/project/sylius :) Good luck 🖖

**Comment by Gregcop1** [comment]
No problem, I didn't know, let's move to this solution. Thanks
I can't find RefundPlugin in the list. Did I missed something? @Zales0123

**Comment by Zales0123** [comment]
Woooooow, what has just happened 😄 Sorry, it's totally my bad, I've just answered automatically and didn't notice it's not a `Sylius/Sylius` repository 💃 We don't have a Crowdin configured for plugins yet, so definitely it's a proper PR. Sorry for the confusion 🖖

**Comment by toucanbleu** [comment]
👍

**Comment by lchrusciel** [comment]
Thank you, Grégory! :1st_place_medal:

**Pull request merged**
