### PR TITLE
Up Symfony Messenger requirement

### PR DESCRIPTION
**Pull request by loevgaard**
No reason to restrict the Symfony Messenger component

### CODE REVIEW

**Review by stloyd — APPROVED** [review]

**Review by Zales0123 — APPROVED** [review]
I'm wondering shouldn't we explicitly specify messenger version in our builds to make a conscious check of this compatibility 🤔 Still, as far as I see, on some builds 4.4 version is installed, on some 5.2, so it should be safe enough to go 🖖

**Review by Zales0123 — CHANGES_REQUESTED** [review]
OK, in fact, it's not that easy :D We didn't require symfony/messenger on Sylius 1.7, but we do on Sylius 1.8... and we require 4.4 version :/ which means, we should wait for the support of this version on `sylius/sylius` itself

**Comment by loevgaard** [comment]
@Zales0123: I don't see why we can't have a `^4.4 || ^5.0` on this requirement. Why would that ever conflict with `sylius/sylius`?

**Comment by Zales0123** [comment]
The conflict is not explicit, we still would be able to use symfony/messenger:^4.4, but we will never be allowed to use ^5.0 with Sylius 1.8 (which, btw, is the only actively supported version now).

Zrzut ekranu 2020-12-18 o 12 53 43

That's why we would not be able to test the build with symfony/messenger:^5.0 and be sure it works 🚀

**Comment by loevgaard** [comment]
I understand, Mateusz :| Hoping for SF5 support 🤞

**Comment by GSadee** [comment]
Closing in favour of https://github.com/Sylius/RefundPlugin/pull/254

**Pull request closed without merging**
