### PR TITLE
Improve french translation

### PR DESCRIPTION
**Pull request by Nek-**
Stands as replacement for #389 

| Q               | A
| --------------- | -----
| Branch?         | 1.2
| Bug fix?        | no
| New feature?    | no

I add a screen so @loic425 understands how wrong it is atm...

image

### CODE REVIEW

**Comment by loic425** [comment]
Indeed, but that's not the translation which is wrong, but the key is.
@Zales0123 @lchrusciel @Ferror Why it is "refund_payments" instead of "refunded_payments" here?

**Comment by Nek-** [comment]
I'm not sure it's a good idea to change a translation key because its content is not precise. People may override translation in their projects so keeping it like this is better.

**Comment by UlrichHP** [comment]
I don't think this is the correct translation, IMHO `Remboursements` is more appropriate. It is in the same style as `Paiements` above it and is more logical because refunds are not always completed, you can have the button to finish it.

**Comment by loic425** [comment]
@Nek- Not changing the key, but adding the key :dagger:

**Pull request closed without merging**
