### PR TITLE
Filtering credit memos

### PR DESCRIPTION
**Pull request by Zales0123**
Based on https://github.com/Sylius/RefundPlugin/pull/45

zrzut ekranu 2018-08-24 o 15 21 07

### CODE REVIEW

**Comment by GSadee** [comment]
Could you rebase?

**Comment by bartoszpietrzak1994** [comment]
Could you add a migration file related to CreditMemoChannel entity in order not to open an additional PR?

**Comment by Zales0123** [comment]
It should be indeed added in the previous PR. Nevertheless, it's fixed now :)

**Comment by Zales0123** [comment]
I was wondering about that, but this is a built-in functionality of `GridBundle`, this filtering functionality is already tested in a bundle and in **Sylius** itself. Even a custom filter is somehow tested, as it fulfills the interface (but this is the place where we could add some test, eventually). 🏹

**Comment by GSadee** [comment]
It won't be a big benefit, so I won't insist on that, but IMO we should cover such tests with behat.

**Comment by Zales0123** [comment]
Ok, I would vote to merge it to have it already in plugin (with no big harm) and think about most effective way to test it, wdyt?

**Comment by GSadee** [comment]
Thank you Matt ⛺️

**Pull request merged**
